### ISSUE TITLE
Unable to connect Pullstring Author, to Local Web API

### ISSUE THREAD

**Issue by jimmyrazo** [pullstring/pullstring-js#3]
Hi,

I am trying to connect pull string to local web api. Getting below error.

"errorMessage":"connect ECONNREFUSED 127.0.0.1:51114","errorType":"Error","stackTrace":["Object.exports._errnoException (util.js:870:11)","exports._exceptionWithHostPort (util.js:893:20)","TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)"]

Below is the debug.js used in Web Api
*************************************************************************

var http = require('http');
var options = {
  host : 'localhost',
    port: 51114,
    path: '/DataService.svc/GetData/100',
    method: 'GET'
};
var req = http.request(options, function(res) {
    var data = '';
    res.setEncoding('utf8');
    res.on('data', function(chunk) {
        data += chunk;
    });
    res.on('end', function() {
        var news = JSON.parse(data);
        if (news['status'] == 'OK') {
            var results = news['results'];

            succeed(results);
        }
    });
});
req.on('error', function(e) {
    fail(e);
});
req.end()
*************************************************************************

Please help urgently.
Thanks 
JR

**Comment by gdamron** [comment]
Is this a question about the PullString Javascript SDK or using [Web Services](http://docs.pullstring.com/docs/web-services) in PullString Author?

If it's the latter, the issue is that you're trying to connect to `localhost`. Web Services run in a sandboxed environment and requires a url that is accessible via the public internet. To continue using your local development environment, I recommend using a tool such as [ngrok](https://ngrok.com) to create a temporary public url.
